<script lang="ts">
  import {page} from '$app/state';
  import {TextInput,EmailInput,NumberInput,Select,MultiSelect,Checkbox,Radio,Textarea,CursorTable,MarkdownView,BusySurface,EmptyState,ErrorState,Toast,Dialog,Drawer,transitionAiOperation,useLocale,type typAiOperationState,type typAiOperationEvent,type intfTableColumn} from '@targoman/ui-core';
  import {DateInput,DateTimeInput,DateRangeInput} from '@targoman/calendar-svelte';
  import {parseTimeZone} from '@targoman/calendar-core';
  const i18n=useLocale();
  const today={calendar:'gregorian' as const,year:2026,month:10,day:2};
  const options=[{value:'a',label:'گزینه نخست'},{value:'b',label:'گزینه دوم'},{value:'c',label:'گزینه سوم'}];
  const icons=[['ناوبری','fa-bars'],['ویرایش','fa-pen'],['حذف','fa-trash'],['جست‌وجو','fa-magnifying-glass'],['ذخیره','fa-floppy-disk'],['بستن','fa-xmark'],['موفق','fa-circle-check'],['هشدار','fa-triangle-exclamation'],['خطا','fa-circle-exclamation'],['ماه پیش',i18n.dir==='rtl'?'fa-arrow-right':'fa-arrow-left'],['ماه بعد',i18n.dir==='rtl'?'fa-arrow-left':'fa-arrow-right'],['بارگذاری','fa-upload'],['دریافت','fa-download']] as const;
  type typRow=Record<string,unknown>&{name:string;code:string;count:string;date:string};
  const rows:typRow[]=[{name:'نمونه یک',code:'Qwen3.5-122B',count:'1250',date:'2026-10-02'},{name:'نمونه دو',code:'RTX 4090',count:'42',date:'2026-09-28'}];
  const columns:intfTableColumn<typRow>[]=[{id:'name',header:'نام',value:row=>row.name,presentation:'rtl'},{id:'code',header:'شناسه فنی',value:row=>row.code,presentation:'ltr'},{id:'count',header:'تعداد',value:row=>row.count,presentation:'fa-num'},{id:'date',header:'تاریخ',value:row=>row.date,presentation:'fa-num'}];
  const firstPage={items:rows,nextCursor:'page-2',hasMore:true},secondPage={items:[rows[1]],nextCursor:null,hasMore:false},emptyPage={items:[] as typRow[],nextCursor:null,hasMore:false};
  const transitions:Record<typAiOperationState,readonly typAiOperationEvent[]>={IDLE:['SUBMIT'],SUBMITTING:['STREAM_START','TERMINAL_SUCCESS','FAIL','CANCEL_ACK','INTERRUPT','OUTCOME_UNKNOWN'],STREAMING:['TERMINAL_SUCCESS','FAIL','CANCEL_ACK','INTERRUPT','OUTCOME_UNKNOWN'],COMPLETING:['CONFIRM_RESULT','FAIL','OUTCOME_UNKNOWN'],SUCCEEDED:['RESET'],FAILED:['RESET'],CANCELLED:['RESET'],INTERRUPTED:['RESET'],UNRESOLVED:['RESET']};
  let textValue=$state('نمونه فارسی'),emailValue=$state('user@example.com'),numberFa=$state('12345'),numberLatin=$state('4090'),selection=$state('a'),selections=$state<readonly string[]>(['a']),checked=$state(true),radio=$state('a'),notes=$state('این یک متن راست‌به‌چپ است.');
  let date=$state('2026-10-02'),invalidDate=$state(''),dateTime=$state({date:'2026-10-02',time:'13:45',timeZone:parseTimeZone('Asia/Tehran')}),range=$state({start:'2026-10-01',end:'2026-10-08'});
  let hidden=$state(true),listMode=$state<'rows'|'loading'|'empty'>('rows'),listPage=$state(1),busy=$state(false),toast=$state(''),dialogOpen=$state(false),drawerOpen=$state(false),aiState=$state<typAiOperationState>('IDLE');
  const urlSample='https:'+'//example.com/path';
  const markdownSource='# متن نمایشی\n\nاین **متن پررنگ** با English content و `inline_code` همراه است.\n\n- مورد اول\n- مورد دوم\n\n[پیوند داخلی](/foundation)\n\n| ستون | مقدار |\n| --- | --- |\n| نمونه | ۱۲۳ |\n\n```ts\nconst sample = 42;\n```';
  const reviewItems=['فونت IRANSansX دیده می‌شود','متن فارسی راست‌به‌چپ است','فیلدهای فنی انگلیسی چپ‌به‌راست هستند','عددها به شکل فارسی نمایش داده می‌شوند','آیکون‌های FontAwesome دیده می‌شوند','پوسته روشن، تیره و سامانه بررسی شد','فرم‌ها و خطاها بررسی شدند','تقویم جلالی و صفحه‌کلید بررسی شد','جدول و فهرست بررسی شد','Markdown بررسی شد','پنجره و کشو بررسی شدند','وضعیت‌های بازخورد بررسی شدند','نمای موبایل و واکنش‌گرا بررسی شد'];
  const rowActions=[{label:'ویرایش ردیف',iconClass:'fa-pen',onClick:(row:typRow)=>toast=`ویرایش ${row.name}`},{label:'حذف ردیف',iconClass:'fa-trash',onClick:(row:typRow)=>toast=`حذف ${row.name}`}];
  function advanceAi(event:typAiOperationEvent){aiState=transitionAiOperation(aiState,event);}
</script>

<div class="foundation-showcase container-fluid pb-5">
  <header class="mb-5"><p class="text-secondary">U1.2 · Development only</p><h2>{i18n.t('foundation')}</h2><p>پیش‌نمایش تعاملی اجزای مشترک رابط کاربری؛ داده‌ها ساختگی‌اند.</p></header>
  <section class="showcase-section" aria-labelledby="brand-heading"><h2 id="brand-heading">{i18n.t('branding')}</h2><div class="row g-3"><div class="col-md-6"><strong>{page.data.bootstrap.brand.displayName}</strong>{#if page.data.bootstrap.brand.logoLight}<img src={page.data.bootstrap.brand.logoLight.path} alt={page.data.bootstrap.brand.logoLight.alt} height="40" />{/if}<p>نام و لوگو از BrandProfile می‌آیند.</p></div><div class="col-md-6"><p>Locale: <code>{i18n.locale}</code> · Direction: <code>{i18n.dir}</code></p><p>انتخاب پوسته و زبان در سربرگ صفحه قرار دارد. اندازه پنجره را برای بررسی پوسته واکنش‌گرا تغییر دهید.</p></div></div></section>
  <section class="showcase-section" aria-labelledby="type-heading"><h2 id="type-heading">{i18n.t('typography')}</h2><p class="fw-normal">IRANSansX Regular — این یک پاراگراف فارسی برای بررسی خوانایی است.</p><p class="fw-medium">IRANSansX Medium — نمونه وزن میانه در متن فارسی.</p><p class="fw-bold">IRANSansX Bold — نمونه متن پررنگ فارسی.</p><h3>عنوان سطح سوم</h3><p lang="en" class="ltr">English paragraph in a local LTR island, set in the default font stack.</p><p>متن آمیخته با <span class="ltr d-inline-block">Qwen3.5-122B</span> در همان سطر فارسی.</p><small class="text-secondary">متن کوچک و راهنمای تکمیلی.</small></section>
  <section class="showcase-section" aria-labelledby="numbers-heading"><h2 id="numbers-heading">{i18n.t('numbers')}</h2><div class="row g-3"><div class="col-md-6"><h3 class="h6">مقدار اصلی ASCII</h3><code class="ltr">1234567890</code></div><div class="col-md-6"><h3 class="h6">نمایش fa-num</h3><span class="fa-num">1234567890</span></div></div><p>تعداد: <strong class="fa-num">1250</strong> · تاریخ: <span class="fa-num">1405/07/10</span> · آمار: <span class="fa-num">4090</span></p></section>
  <section class="showcase-section" aria-labelledby="direction-heading"><h2 id="direction-heading">{i18n.t('direction')}</h2><div class="row g-3"><div class="col-md-6 ltr border rounded p-3"><strong>LTR</strong><p>user@example.com<br />{urlSample}<br />Qwen3.5-122B<br />RTX 4090</p></div><div class="col-md-6 rtl border rounded p-3"><strong>RTL</strong><p>برچسب و محتوای فارسی در یک ناحیه مستقل راست‌به‌چپ.</p></div></div><button type="button" class="btn btn-outline-primary mt-3" onclick={()=>hidden=!hidden}>{hidden?'نمایش محتوای پنهان':'پنهان کردن محتوا'}</button><span class:hidden={hidden} class="ms-3">محتوای آزمایشی برای ابزار .hidden</span></section>
  <section class="showcase-section" aria-labelledby="icons-heading"><h2 id="icons-heading">{i18n.t('icons')}</h2><div class="d-flex flex-wrap gap-3">{#each icons as [label,icon]}<div class="text-center border rounded p-2 icon-sample"><i class={`fa-solid ${icon}`} aria-hidden="true"></i><small class="d-block">{label}</small></div>{/each}</div></section>
  <section class="showcase-section" aria-labelledby="forms-heading"><h2 id="forms-heading">{i18n.t('forms')}</h2><div class="row g-4"><div class="col-lg-4"><h3 class="h6">حالت معمول و راهنما</h3><TextInput id="show-text" label="نام نمایشی" value={textValue} onChange={next=>textValue=next} help="نام را به فارسی وارد کنید." /><EmailInput id="show-email" label="رایانامه" value={emailValue} onChange={next=>emailValue=next} help="ورودی انگلیسی در صفحه فارسی" /><NumberInput id="show-number-fa" label="تعداد با نمایش فارسی" value={numberFa} onChange={next=>numberFa=next} mode="integer" faNum={true} /><NumberInput id="show-number-latin" label="شناسه عددی لاتین" value={numberLatin} onChange={next=>numberLatin=next} mode="integer" faNum={false} dir="ltr" /><p>مقدار ذخیره‌شده: <code>{numberFa}</code> / <code>{numberLatin}</code></p></div><div class="col-lg-4"><h3 class="h6">انتخاب و متن</h3><Select id="show-select" label="گزینه" value={selection} {options} onChange={next=>selection=next} /><MultiSelect id="show-multi" label="چند گزینه" values={selections} {options} onChange={next=>selections=next} /><Checkbox id="show-check" label="تأیید آزمایشی" {checked} onChange={next=>checked=next} /><Radio id="show-radio-a" name="show-radio" label="گزینه اول" value="a" selected={radio} onChange={next=>radio=next} /><Radio id="show-radio-b" name="show-radio" label="گزینه دوم" value="b" selected={radio} onChange={next=>radio=next} /><Textarea id="show-notes" label="توضیح فارسی" value={notes} onChange={next=>notes=next} dir="rtl" /></div><div class="col-lg-4"><h3 class="h6">غیرفعال و خطا</h3><TextInput id="show-text-disabled" label="متن غیرفعال" value="نمونه" onChange={()=>undefined} disabled /><TextInput id="show-text-error" label="متن نامعتبر" value="" onChange={()=>undefined} error="این فیلد الزامی است." /><EmailInput id="show-email-error" label="رایانامه نامعتبر" value="bad" onChange={()=>undefined} error="نشانی رایانامه معتبر نیست." /><NumberInput id="show-number-error" label="عدد نامعتبر" value="" onChange={()=>undefined} mode="integer" error="عدد را وارد کنید." /><Select id="show-select-disabled" label="انتخاب غیرفعال" value="a" {options} onChange={()=>undefined} disabled /><MultiSelect id="show-multi-error" label="چند انتخاب نامعتبر" values={[]} {options} onChange={()=>undefined} error="یک گزینه انتخاب کنید." /><Checkbox id="show-check-disabled" label="تأیید غیرفعال" checked={false} onChange={()=>undefined} disabled /><Radio id="show-radio-disabled" name="show-radio-disabled" label="رادیوی غیرفعال" value="a" selected="" onChange={()=>undefined} disabled /><Textarea id="show-notes-error" label="توضیح نامعتبر" value="" onChange={()=>undefined} error="توضیح لازم است." /></div></div></section>
  <section class="showcase-section" aria-labelledby="calendar-heading"><h2 id="calendar-heading">{i18n.t('calendar')}</h2><div class="row g-4"><div class="col-md-4"><DateInput id="show-date" label="تاریخ انتخابی" value={date} {today} onChange={next=>date=next} /><p>مقدار اصلی: <code>{date}</code></p></div><div class="col-md-4"><DateTimeInput id="show-datetime" label="تاریخ و ساعت" date={dateTime.date} time={dateTime.time} timeZone={dateTime.timeZone} {today} onChange={next=>dateTime=next} /><p>مقدار اصلی: <code>{dateTime.date}T{dateTime.time} [{dateTime.timeZone}]</code></p></div><div class="col-md-4"><DateRangeInput id="show-range" label="بازه تاریخ" start={range.start} end={range.end} {today} onChange={next=>range=next} /><p>مقدار اصلی: <code>{range.start} / {range.end}</code></p></div></div><div class="row g-4"><div class="col-md-4"><DateInput id="show-date-disabled" label="تاریخ غیرفعال" value="2026-10-02" {today} onChange={()=>undefined} disabled /></div><div class="col-md-4"><DateInput id="show-date-error" label="تاریخ نامعتبر" value={invalidDate} {today} onChange={next=>invalidDate=next} error="تاریخ را انتخاب کنید." /></div></div></section>
  <section class="showcase-section" aria-labelledby="table-heading"><h2 id="table-heading">{i18n.t('table')}</h2><div class="btn-group mb-3" role="group" aria-label="حالت جدول"><button type="button" class="btn btn-outline-primary" onclick={()=>listMode='rows'}>ردیف‌ها</button><button type="button" class="btn btn-outline-primary" onclick={()=>listMode='loading'}>بارگذاری</button><button type="button" class="btn btn-outline-primary" onclick={()=>listMode='empty'}>خالی</button></div><CursorTable page={listMode==='empty'?emptyPage:listPage===1?firstPage:secondPage} {columns} caption="داده آزمایشی فارسی" loading={listMode==='loading'} actions={rowActions} onMore={()=>listPage=2} /><p>صفحه: <span class="fa-num">{listPage}</span> · نشانگر ادامه: <code>{listPage===1?'page-2':'null'}</code> · شمار کل درخواست نشده است.</p></section>
  <section class="showcase-section" aria-labelledby="markdown-heading"><h2 id="markdown-heading">{i18n.t('markdown')}</h2><MarkdownView source={markdownSource} /></section>
  <section class="showcase-section" aria-labelledby="feedback-heading"><h2 id="feedback-heading">{i18n.t('feedback')}</h2><button type="button" class="btn btn-outline-primary me-2" onclick={()=>busy=!busy}>{busy?'توقف بارگذاری':'نمایش بارگذاری'}</button><button type="button" class="btn btn-outline-primary me-2" onclick={()=>toast='عملیات نمایشی انجام شد.'}>نمایش پیام</button><button type="button" class="btn btn-outline-secondary" onclick={()=>toast=''}>پاک کردن پیام</button><BusySurface scope="panel" {busy} status="در حال بارگذاری بخش نمایشی"><div class="border rounded p-3 mt-3">محتوای بخش آزمایشی</div></BusySurface><EmptyState title="هنوز داده‌ای وجود ندارد" description="برای شروع یک مورد اضافه کنید." /><ErrorState title="خطای آزمایشی" description="درخواست نمونه انجام نشد؛ دوباره تلاش کنید." />{#if toast}<Toast message={toast} kind="success" />{/if}</section>
  <section class="showcase-section" aria-labelledby="overlays-heading"><h2 id="overlays-heading">{i18n.t('overlays')}</h2><button type="button" class="btn btn-primary me-2" onclick={()=>dialogOpen=true}>باز کردن پنجره</button><button type="button" class="btn btn-outline-primary" onclick={()=>drawerOpen=true}>باز کردن کشو</button><Dialog id="show-dialog" title="پنجره نمایشی" open={dialogOpen} onClose={()=>dialogOpen=false} description="کلید Escape را برای بستن امتحان کنید."><p>محتوای فارسی پنجره.</p><button type="button" class="btn btn-primary" onclick={()=>dialogOpen=false}><i class="fa-solid fa-check" aria-hidden="true"></i> تأیید</button></Dialog><Drawer id="show-drawer" title="کشوی نمایشی" open={drawerOpen} onClose={()=>drawerOpen=false}><p>محتوای فارسی کشو و بررسی بازگشت فوکوس.</p><button type="button" class="btn btn-primary" onclick={()=>drawerOpen=false}><i class="fa-solid fa-check" aria-hidden="true"></i> تأیید</button></Drawer></section>
  <section class="showcase-section" aria-labelledby="ai-heading"><h2 id="ai-heading">{i18n.t('aiStates')}</h2><p>شبیه‌ساز دیداری بدون اتصال به مدل یا ارائه‌دهنده.</p><output class="badge text-bg-primary">{aiState}</output>{#if aiState==='STREAMING'}<p role="status">بخشی از پاسخ در حال دریافت است…</p>{:else if aiState==='SUBMITTING'||aiState==='COMPLETING'}<p role="status">عملیات در حال انجام است…</p>{:else if aiState==='FAILED'}<ErrorState title="خطای نمونه" description="عملیات نمایشی شکست خورد." />{:else if aiState==='INTERRUPTED'}<p>پاسخ ناقص باقی ماند.</p>{:else if aiState==='SUCCEEDED'}<Toast message="پاسخ نمونه تکمیل شد." kind="success" />{:else if aiState==='UNRESOLVED'}<p>نتیجه نامشخص است و نیاز به بررسی دارد.</p>{:else if aiState==='CANCELLED'}<p>عملیات لغو شد.</p>{/if}<div class="d-flex flex-wrap gap-2 mt-3">{#each transitions[aiState] as event}<button type="button" class="btn btn-outline-primary" onclick={()=>advanceAi(event)}>{event==='CANCEL_ACK'?'لغو':event}</button>{/each}</div></section>
  <section class="showcase-section" aria-labelledby="review-heading"><h2 id="review-heading">{i18n.t('review')}</h2><ul class="review-list">{#each reviewItems as item}<li><label><input type="checkbox" /> {item}</label></li>{/each}</ul><p class="text-secondary">این فهرست برای بازبینی انسانی است و نتیجه خودکار تولید نمی‌کند.</p></section>
</div>
<style>.showcase-section{padding-block:1.5rem;border-block-start:1px solid var(--bs-border-color)}.showcase-section>h2{font-size:1.35rem;margin-block-end:1rem}.icon-sample{min-width:6rem}.icon-sample i{font-size:1.25rem}.review-list{columns:2;list-style:none;padding:0}.review-list li{break-inside:avoid;padding-block:.25rem}@media(max-width:720px){.review-list{columns:1}}</style>
